#!/usr/bin/env bash
# Tux Browser Build Script
# 
# This script builds Tux Browser (Chromium + Tor integration)
# 
# Usage: ./build_tux_browser.sh [options]
# Options:
#   --out-dir=DIR       Output directory (default: out/tux_browser)
#   --target=TARGET     Build target (default: chrome)
#   --jobs=N            Number of parallel jobs (default: auto)
#   --clean             Clean build directory before building
#   --help              Show this help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHROMIUM_SRC="${SCRIPT_DIR}/chromium-main/chromium-main"
DEFAULT_OUT_DIR="${CHROMIUM_SRC}/out/tux_browser"
DEFAULT_TARGET="chrome"
DEFAULT_JOBS=$(nproc)

OUT_DIR="${DEFAULT_OUT_DIR}"
TARGET="${DEFAULT_TARGET}"
JOBS="${DEFAULT_JOBS}"
CLEAN=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --out-dir=*)
      OUT_DIR="${1#*=}"
      shift
      ;;
    --target=*)
      TARGET="${1#*=}"
      shift
      ;;
    --jobs=*)
      JOBS="${1#*=}"
      shift
      ;;
    --clean)
      CLEAN=true
      shift
      ;;
    --help)
      echo "Tux Browser Build Script"
      echo ""
      echo "Usage: $0 [options]"
      echo "Options:"
      echo "  --out-dir=DIR       Output directory (default: out/tux_browser)"
      echo "  --target=TARGET     Build target (default: chrome)"
      echo "  --jobs=N            Number of parallel jobs (default: $(nproc))"
      echo "  --clean             Clean build directory before building"
      echo "  --help              Show this help"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

echo "=========================================="
echo "Tux Browser Build"
echo "=========================================="
echo "Chromium source: ${CHROMIUM_SRC}"
echo "Output directory: ${OUT_DIR}"
echo "Build target: ${TARGET}"
echo "Jobs: ${JOBS}"
echo "Clean: ${CLEAN}"
echo ""

# Check if we're in the right directory
if [[ ! -f "${CHROMIUM_SRC}/BUILD.gn" ]]; then
  echo "ERROR: Chromium source not found at ${CHROMIUM_SRC}"
  exit 1
fi

cd "${CHROMIUM_SRC}"

# Clean if requested
if [[ "${CLEAN}" == "true" ]]; then
  echo "Cleaning build directory..."
  rm -rf "${OUT_DIR}"
fi

# Create args.gn for Tux Browser
echo "Generating build configuration..."
mkdir -p "${OUT_DIR}"
cat > "${OUT_DIR}/args.gn" << EOF
# Tux Browser Build Configuration
# Generated by build_tux_browser.sh

# Tux Browser branding
is_tux_browser = true

# Enable Tor integration
enable_tor = true

# Disable Google services for privacy
enable_google_services = false
enable_chrome_extensions = true
enable_widevine = false
proprietary_codecs = false
ffmpeg_branding = "Chrome"

# Disable metrics and crash reporting
enable_metrics_reporting = false
enable_crash_reporter = false

# Safe browsing (0 = disabled)
safe_browsing_mode = 0

# Build type
is_official_build = false
is_debug = false
symbol_level = 1

# Optimization
is_component_build = false
use_thin_lto = true

# Enable Tor networking stack
enable_tor_networking = true

# Use system libraries where possible
use_system_icu = true
use_system_libjpeg = true
use_system_libpng = true
use_system_zlib = true
use_system_freetype = true
use_system_harfbuzz = true

# Disable NaCl (not needed)
enable_nacl = false
enable_nacl_nonsfi = false

# V8 snapshot
v8_use_snapshot = true
v8_enable_slow_dchecks = false

# PDFium
pdf_use_skia = true
pdf_use_skia_paths = true

# Skia
skia_use_system_expat = false
skia_use_system_icu = false
skia_use_system_libjpeg_turbo = false
skia_use_system_libpng = false
skia_use_system_libwebp = false
skia_use_system_zlib = false

# Angle (for GPU)
angle_enable_vulkan = true
angle_enable_swiftshader = false

# Enable JIT
v8_enable_webassembly = true

# Enable WebRTC (but we'll block it at runtime for privacy)
enable_webrtc = true

# Disable some features for privacy
enable_background_networking = false
enable_default_apps = false
enable_autofill = false
enable_password_manager = false
enable_sync = false
enable_translate = false
enable_spellcheck = false
enable_printing = true
enable_cast = false
enable_mdns = false
enable_nearby = false
enable_quickshare = false

# Target OS/CPU (adjust as needed)
# target_os = "linux"
# target_cpu = "x64"
EOF

echo "Build configuration written to ${OUT_DIR}/args.gn"

# Run gn gen
echo "Running gn gen..."
gn gen "${OUT_DIR}" --fail-on-unused-args

# Build
echo "Building ${TARGET}..."
autoninja -C "${OUT_DIR}" "${TARGET}" -j "${JOBS}"

echo ""
echo "=========================================="
echo "Build completed successfully!"
echo "=========================================="
echo "Binary location: ${OUT_DIR}/${TARGET}"
echo ""
echo "To run Tux Browser:"
echo "  ${OUT_DIR}/${TARGET} --enable-features=TorNetworking"
echo ""
echo "Note: Tor must be installed and running on localhost:9050"
echo "Or use the embedded Tor (requires additional setup)"