@echo off
REM Tux Browser Build Script for Windows (Batch version)
REM Usage: build_tux_browser.bat [--clean] [--jobs=N] [--target=TARGET] [--out-dir=DIR]

setlocal enabledelayedexpansion

set SCRIPT_DIR=%~dp0
set CHROMIUM_SRC=%SCRIPT_DIR%chromium-main\chromium-main
set OUT_DIR=%CHROMIUM_SRC%\out\tux_browser
set TARGET=chrome
set JOBS=0
set CLEAN=0

REM Parse arguments
:PARSE_ARGS
if "%~1"=="" goto PARSE_DONE
if "%~1"=="--clean" set CLEAN=1 & shift & goto PARSE_ARGS
if "%~1"=="--help" goto SHOW_HELP
if "%~1"=="-h" goto SHOW_HELP
if "%~1"=="--jobs" if not "%~2"=="" set JOBS=%~2 & shift & shift & goto PARSE_ARGS
if "%~1"=="--target" if not "%~2"=="" set TARGET=%~2 & shift & shift & goto PARSE_ARGS
if "%~1"=="--out-dir" if not "%~2"=="" set OUT_DIR=%CHROMIUM_SRC%\%~2 & shift & shift & goto PARSE_ARGS
shift
goto PARSE_ARGS

:PARSE_DONE

if %JOBS%==0 (
    for /f %%i in ('wmic cpu get NumberOfLogicalProcessors ^| findstr /r "[0-9]"') do set JOBS=%%i
)

echo ==========================================
echo Tux Browser Build
echo ==========================================
echo Chromium source: %CHROMIUM_SRC%
echo Output directory: %OUT_DIR%
echo Build target: %TARGET%
echo Jobs: %JOBS%
echo Clean: %CLEAN%
echo.

REM Check if we're in the right directory
if not exist "%CHROMIUM_SRC%\BUILD.gn" (
    echo ERROR: Chromium source not found at %CHROMIUM_SRC%
    exit /b 1
)

cd /d "%CHROMIUM_SRC%"

REM Clean if requested
if %CLEAN%==1 (
    echo Cleaning build directory...
    if exist "%OUT_DIR%" rmdir /s /q "%OUT_DIR%"
)

REM Create args.gn for Tux Browser
echo Generating build configuration...
if not exist "%OUT_DIR%" mkdir "%OUT_DIR%"

(
    echo # Tux Browser Build Configuration
    echo # Generated by build_tux_browser.bat
    echo.
    echo # Tux Browser branding
    echo is_tux_browser = true
    echo.
    echo # Enable Tor integration
    echo enable_tor = true
    echo.
    echo # Disable Google services for privacy
    echo enable_google_services = false
    echo enable_chrome_extensions = true
    echo enable_widevine = false
    echo proprietary_codecs = false
    echo ffmpeg_branding = "Chrome"
    echo.
    echo # Disable metrics and crash reporting
    echo enable_metrics_reporting = false
    echo enable_crash_reporter = false
    echo.
    echo # Safe browsing (0 = disabled)
    echo safe_browsing_mode = 0
    echo.
    echo # Build type
    echo is_official_build = false
    echo is_debug = false
    echo symbol_level = 1
    echo.
    echo # Optimization
    echo is_component_build = false
    echo use_thin_lto = true
    echo.
    echo # Enable Tor networking stack
    echo enable_tor_networking = true
    echo.
    echo # Use system libraries where possible
    echo use_system_icu = false
    echo use_system_libjpeg = false
    echo use_system_libpng = false
    echo use_system_zlib = false
    echo use_system_freetype = false
    echo use_system_harfbuzz = false
    echo.
    echo # Disable NaCl (not needed)
    echo enable_nacl = false
    echo enable_nacl_nonsfi = false
    echo.
    echo # V8 snapshot
    echo v8_use_snapshot = true
    echo v8_enable_slow_dchecks = false
    echo.
    echo # PDFium
    echo pdf_use_skia = true
    echo pdf_use_skia_paths = true
    echo.
    echo # Skia
    echo skia_use_system_expat = false
    echo skia_use_system_icu = false
    echo skia_use_system_libjpeg_turbo = false
    echo skia_use_system_libpng = false
    echo skia_use_system_libwebp = false
    echo skia_use_system_zlib = false
    echo.
    echo # Angle (for GPU)
    echo angle_enable_vulkan = true
    echo angle_enable_swiftshader = false
    echo.
    echo # Enable JIT
    echo v8_enable_webassembly = true
    echo.
    echo # Enable WebRTC (but we'll block it at runtime for privacy)
    echo enable_webrtc = true
    echo.
    echo # Disable some features for privacy
    echo enable_background_networking = false
    echo enable_default_apps = false
    echo enable_autofill = false
    echo enable_password_manager = false
    echo enable_sync = false
    echo enable_translate = false
    echo enable_spellcheck = false
    echo enable_printing = true
    echo enable_cast = false
    echo enable_mdns = false
    echo enable_nearby = false
    echo enable_quickshare = false
) > "%OUT_DIR%\args.gn"

echo Build configuration written to %OUT_DIR%\args.gn

REM Run gn gen
echo Running gn gen...
gn gen "%OUT_DIR%" --fail-on-unused-args
if errorlevel 1 (
    echo ERROR: gn gen failed
    exit /b 1
)

REM Build
echo Building %TARGET%...
autoninja -C "%OUT_DIR%" %TARGET% -j %JOBS%
if errorlevel 1 (
    echo ERROR: Build failed
    exit /b 1
)

echo.
echo ==========================================
echo Build completed successfully!
echo ==========================================
echo Binary location: %OUT_DIR%\%TARGET%.exe
echo.
echo To run Tux Browser:
echo   %OUT_DIR%\%TARGET%.exe --enable-features=TorNetworking
echo.
echo Note: Tor must be installed and running on localhost:9050
echo Or use the embedded Tor (requires additional setup)
exit /b 0

:SHOW_HELP
echo Tux Browser Build Script
echo.
echo Usage: build_tux_browser.bat [options]
echo Options:
echo   --clean            Clean build directory before building
echo   --jobs=N           Number of parallel jobs (default: all cores)
echo   --target=TARGET    Build target (default: chrome)
echo   --out-dir=DIR      Output directory (default: out/tux_browser)
echo   --help             Show this help
exit /b 0