<# 
.SYNOPSIS
    Tux Browser Build Script for Windows

.DESCRIPTION
    Builds Tux Browser (Chromium + Tor integration) on Windows

.PARAMETER OutDir
    Output directory (default: out/tux_browser)

.PARAMETER Target
    Build target (default: chrome)

.PARAMETER Jobs
    Number of parallel jobs (default: all cores)

.PARAMETER Clean
    Clean build directory before building

.EXAMPLE
    .\build_tux_browser.ps1 --Clean

.EXAMPLE
    .\build_tux_browser.ps1 --Jobs 8 --Target chrome
#>

param(
    [string]$OutDir = "out/tux_browser",
    [string]$Target = "chrome",
    [int]$Jobs = 0,
    [switch]$Clean,
    [switch]$Help
)

if ($Help) {
    Write-Host "Tux Browser Build Script" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Usage: .\build_tux_browser.ps1 [options]"
    Write-Host "Options:"
    Write-Host "  --OutDir=DIR       Output directory (default: out/tux_browser)"
    Write-Host "  --Target=TARGET    Build target (default: chrome)"
    Write-Host "  --Jobs=N           Number of parallel jobs (default: all cores)"
    Write-Host "  --Clean            Clean build directory before building"
    Write-Host "  --Help             Show this help"
    exit 0
}

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$ChromiumSrc = Join-Path $ScriptDir "chromium-main\chromium-main"
$DefaultOutDir = Join-Path $ChromiumSrc $OutDir

if ($Jobs -eq 0) {
    $Jobs = [System.Environment]::ProcessorCount
}

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "Tux Browser Build" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "Chromium source: $ChromiumSrc"
Write-Host "Output directory: $DefaultOutDir"
Write-Host "Build target: $Target"
Write-Host "Jobs: $Jobs"
Write-Host "Clean: $Clean"
Write-Host ""

# Check if we're in the right directory
if (-not (Test-Path (Join-Path $ChromiumSrc "BUILD.gn"))) {
    Write-Error "ERROR: Chromium source not found at $ChromiumSrc"
    exit 1
}

Set-Location $ChromiumSrc

# Clean if requested
if ($Clean) {
    Write-Host "Cleaning build directory..." -ForegroundColor Yellow
    if (Test-Path $DefaultOutDir) {
        Remove-Item -Recurse -Force $DefaultOutDir
    }
}

# Create args.gn for Tux Browser
Write-Host "Generating build configuration..." -ForegroundColor Yellow
New-Item -ItemType Directory -Force -Path $DefaultOutDir | Out-Null

$ArgsGn = @"
# Tux Browser Build Configuration
# Generated by build_tux_browser.ps1

# Tux Browser branding
is_tux_browser = true

# Enable Tor integration
enable_tor = true

# Disable Google services for privacy
enable_google_services = false
enable_chrome_extensions = true
enable_widevine = false
proprietary_codecs = false
ffmpeg_branding = "Chrome"

# Disable metrics and crash reporting
enable_metrics_reporting = false
enable_crash_reporter = false

# Safe browsing (0 = disabled)
safe_browsing_mode = 0

# Build type
is_official_build = false
is_debug = false
symbol_level = 1

# Optimization
is_component_build = false
use_thin_lto = true

# Enable Tor networking stack
enable_tor_networking = true

# Use system libraries where possible
use_system_icu = false
use_system_libjpeg = false
use_system_libpng = false
use_system_zlib = false
use_system_freetype = false
use_system_harfbuzz = false

# Disable NaCl (not needed)
enable_nacl = false
enable_nacl_nonsfi = false

# V8 snapshot
v8_use_snapshot = true
v8_enable_slow_dchecks = false

# PDFium
pdf_use_skia = true
pdf_use_skia_paths = true

# Skia
skia_use_system_expat = false
skia_use_system_icu = false
skia_use_system_libjpeg_turbo = false
skia_use_system_libpng = false
skia_use_system_libwebp = false
skia_use_system_zlib = false

# Angle (for GPU)
angle_enable_vulkan = true
angle_enable_swiftshader = false

# Enable JIT
v8_enable_webassembly = true

# Enable WebRTC (but we'll block it at runtime for privacy)
enable_webrtc = true

# Disable some features for privacy
enable_background_networking = false
enable_default_apps = false
enable_autofill = false
enable_password_manager = false
enable_sync = false
enable_translate = false
enable_spellcheck = false
enable_printing = true
enable_cast = false
enable_mdns = false
enable_nearby = false
enable_quickshare = false
"@

$ArgsGn | Set-Content -Path (Join-Path $DefaultOutDir "args.gn") -Encoding UTF8
Write-Host "Build configuration written to $DefaultOutDir\args.gn" -ForegroundColor Green

# Run gn gen
Write-Host "Running gn gen..." -ForegroundColor Yellow
gn gen $OutDir --fail-on-unused-args

# Build
Write-Host "Building $Target..." -ForegroundColor Yellow
autoninja -C $OutDir $Target -j $Jobs

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "Build completed successfully!" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "Binary location: $DefaultOutDir\$Target.exe" -ForegroundColor Green
Write-Host ""
Write-Host "To run Tux Browser:" -ForegroundColor Cyan
Write-Host "  $DefaultOutDir\$Target.exe --enable-features=TorNetworking"
Write-Host ""
Write-Host "Note: Tor must be installed and running on localhost:9050" -ForegroundColor Yellow
Write-Host "Or use the embedded Tor (requires additional setup)" -ForegroundColor Yellow